# Generated by Django 3.0.4 on 2020-03-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=512)),
                ('short_url', models.CharField(max_length=64)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('last_check_status', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
