# Generated by Django 3.0.4 on 2020-03-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='short_url',
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(max_length=512, unique=True),
        ),
    ]
